# NumPy

## 1. PyData Ecosystem

IPython/Jupyter: simple, sharable notebooks

NumPy: Underlying abstraction that sits below basically all of the libraries 
    - contains an efficient n-dimensional array representaton 
 
pandas: Excellent data manipulation framework that is more user friendly interface for NymPy and SciPy

MatPlotLib: Plotting and graphics library
    - Godd integration with pandas

Not Covered in calss:
    - SciPy: Scientific computing framework that sits on top of NumPy
    - Scikit-Lean/Scikit-Image: Machine learning library

PyData is the mot popuular data analysis/numerical processing ecosystem in Python.
    - Used frequently over the coming months 
    - Intergarl to data science using Python 

## 2. Functional Programming and Data Manipulation

In [4]:
class Drone:
    power_system = "battery"
    def fly(self):
        return "The %s powered drone is flying" % (self.power_system)
d = Drone()    

In [5]:
def drone_flyer(drone):
    print(drone.fly())

In [6]:
drone_flyer(d)

The battery powered drone is flying


In [8]:
d.power_system = "Subway - Eat Fresh"

In [10]:
drone_flyer(d)

The Subway - Eat Fresh powered drone is flying


In [13]:
d = Drone()

def drone_changer():
    d.power_system = "I've made a huge mistake"
print(d.fly())
drone_changer()
print(d.fly())

The battery powered drone is flying
The I've made a huge mistake powered drone is flying


**Functional Programming**

The result of a function should only depend on the inputs passed into the function. Instead of using objects with mutable state, functional programmers organize program into functions, none of which has side effects. One of the reasons why functions programming is code reliability. Another reason is that functional programming gives good modularity.

### Maping

- A traditional way of making a list of x^3

In [22]:
x= range(0,10)
def cube(num):
    return num ** 3
new_list = []
for item in x:
    new_list.append(cube(item))
print(new_list)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


- Use mapping method 

In [29]:
map_list = map(cube,x)   # map a function over a value 
print(list(map_list))

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]


In [31]:
map_list

In [32]:
# the above mapping method is called a lazy evaluation because until we ask 
# it for the specific values, (e.g. we try to convert it into a list) Python
# will store the execution and only executed when it is needed 

### Filter 

filter a list and left only the values that meet the requirement

In [34]:
x

range(0, 10)

In [36]:
def divis_by_2(num):
    return num % 2 == 0

In [37]:
divis_by_2(4)

True

In [38]:
divis_by_2(5)

False

In [41]:
list(map(divis_by_2,x))

[True, False, True, False, True, False, True, False, True, False]

In [43]:
list(filter(divis_by_2,x))

[0, 2, 4, 6, 8]

In [44]:
test_list = [
    "hello",
    "x,y,z. i like this.",
    "this is two xx",
    "this, x, here x is, here it is againx"
]

In [45]:
def has_2x(my_string):
    return my_string.count("x") >= 2

In [46]:
has_2x("hello")

False

In [47]:
has_2x("xx,hello")

True

In [59]:
list(filter(has_2x,test_list))

['this is two xx', 'this, x, here x is, here it is againx']

In [64]:
def to_caps(my_string):
    return my_string.capitalize()

In [65]:
list(map(to_caps,filter(has_2x,test_list)))

['This is two xx', 'This, x, here x is, here it is againx']

In [66]:
x = range(10)
[item ** 3 for item in x]

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [67]:
[item * 2 for item in x]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [69]:
[item * 2 for item in x if item % 3 ==0]
# first check is item%3==0 than for true do doubling

[0, 6, 12, 18]

In [70]:
[float(item) for item in x]

[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]

In [71]:
def cube_if(num):
    if num %3 ==0:
        return num * 3 
    else:
        return num *2

In [72]:
[cube_if(item) for item in x]

[0, 2, 4, 9, 8, 10, 18, 14, 16, 27]

In [73]:
list(map(cube_if,x))

[0, 2, 4, 9, 8, 10, 18, 14, 16, 27]

## lambda function 

are functions that are anonamous

In [81]:
# Let's try several ways to square a list 

In [76]:
[item ** 2 for item in x]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [77]:
def square(num):
    return num**2

In [78]:
[square(z) for z in x]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [79]:
list(map(square,x))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [80]:
list(map(lambda i: i**2,x))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [83]:
square_lambda = lambda i:i**2   # we can also give the function a name!

In [84]:
list(map(square_lambda,x))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [85]:
type(square)

function

In [88]:
list(map(lambda j:j**2, filter( lambda z: z % 2 == 0, range(1,20))))

[4, 16, 36, 64, 100, 144, 196, 256, 324]

In [91]:
# the above is the same as the following in the past
my_range = range(1,20)
output = []
for z in my_range:
    if z % 2 == 0:
        output.append(z**2)
print(output)        

[4, 16, 36, 64, 100, 144, 196, 256, 324]


## NumPy Basics of Boolean Selection and Types

In [2]:
import sys
print(sys.version)

3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]


In [3]:
import numpy as np
print(np.__version__)

1.10.4


In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.arange(10)

In [100]:
a.mean()

4.5

In [101]:
a.sum()

45

In [103]:
a.min()

0

In [104]:
a.std()

2.8722813232690143

In [8]:
%timeit[x*x for x in a ]

The slowest run took 4.29 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.69 µs per loop


In [11]:
%timeit a*a

The slowest run took 23.55 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 509 ns per loop


In [13]:
a*a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [14]:
[x*x for x in a ]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [15]:
a = np.arange(20)

In [16]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
[x for x in a if x %2 ==0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [18]:
a[a % 2 == 0] #in numpy, you can simply do this!

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False], dtype=bool)

In [21]:
list(map(lambda x : x % 2 ==0,a ))

[True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False,
 True,
 False]

In [22]:
np2 = np.arange(20000)

In [23]:
%timeit[x for x in np2 if x %2 ==0]

100 loops, best of 3: 6.03 ms per loop


In [24]:
%timeit np2[np2 % 2 == 0]

1000 loops, best of 3: 203 µs per loop


In [27]:
a[(a>15)|(a<5)]

array([ 0,  1,  2,  3,  4, 16, 17, 18, 19])

In [83]:
npa = np.arange(25)

In [30]:
print(type(npa))

<class 'numpy.ndarray'>


In [33]:
npa.dtype

dtype('int32')

In [35]:
np.float64(25)

25.0

In [39]:
np.float32(npa)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.], dtype=float32)

In [40]:
np.array([1.0,0,2,3]).dtype

dtype('float64')

In [43]:
np.array([True,2,2.0]).dtype

dtype('float64')

In [49]:
np.array([True,2,2.0], dtype = 'uint')

array([1, 2, 2], dtype=uint32)

In [50]:
np.array([True,2,2.0], dtype = 'bool')

array([ True,  True,  True], dtype=bool)

In [61]:
npa # one dimensional array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
npa.size

25

In [84]:
npa.shape  # because this is a one dimensional array, the result will only
            #one dinension. As we have higher dimensions we will have 
            # different shapes!

(25,)

In [85]:
npa.argmin()

0

In [89]:
npa.argmax()

24

In [90]:
print(npa.min(), npa.max(), npa.std(), npa.var())

0 24 7.21110255093 52.0


In [92]:
np.linspace(1,2,5)

array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [94]:
np.linspace(0,10,11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

## NumPy Vectorization and Multidimensional Arrays

In [66]:
# doing operations in a metrix leval, instead of a single number 
import numpy as np
print(np.__version__)

1.10.4


In [77]:
npa = np.random.random_integers(0,50,20)

In [78]:
npa

array([ 3, 19, 43, 25, 23, 40,  3, 20, 44, 32, 17, 24, 29, 30, 47, 49, 33,
       16, 49, 35])

In [79]:
npa *2

array([ 6, 38, 86, 50, 46, 80,  6, 40, 88, 64, 34, 48, 58, 60, 94, 98, 66,
       32, 98, 70])

In [80]:
npa ** 3


array([    27,   6859,  79507,  15625,  12167,  64000,     27,   8000,
        85184,  32768,   4913,  13824,  24389,  27000, 103823, 117649,
        35937,   4096, 117649,  42875], dtype=int32)

In [82]:
npa ** 2 ** 3

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in power
  if __name__ == '__main__':


array([       6561, -2147483648, -2147483648, -2147483648, -2147483648,
       -2147483648,        6561, -2147483648, -2147483648, -2147483648,
       -2147483648, -2147483648, -2147483648, -2147483648, -2147483648,
       -2147483648, -2147483648, -2147483648, -2147483648, -2147483648], dtype=int32)